[package]
name = "rust12-part2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.8.2"
lazy_static = "1.4.0"
num = "0.4.0"
rayon = "1.5"
