cc_library(
    name = "tlpi",
    hdrs = [
        "error_functions.h",
        "get_num.h",
        "tlpi.h"
    ],
    srcs = [
        "error_functions.c",
        "get_num.c",
    ],
    visibility = ["//visibility:public"]
)
